### ISSUE TITLE
Backup and restore OneDrive file permissions

### ISSUE THREAD

**Issue by meain** [alcionai/corso#1774]
https://github.com/alcionai/corso-roadmap/issues/13

### TODO
- [x] Prevent name collisions when another file with `.meta` suffix is present
- [x] Handle cases where children have more permissions than parent along with the nested permissins
- [x] Handle cases where children have less permissions than parent
- [ ] Consider file tree a/b, if we first give user1 access to b, then give user1 access to a and remove user1 access to a, they should retain access to b. This is not available after restore.

**Comment by gmatev** [comment]
> Consider file tree a/b, if we first give user1 access to b, then give user1 access to a and remove user1 access to a, they should retain access to b. This is not available after restore.
This I think is tricky since it may have unintended side effects - I don't want the restore of item b to change the permissions of my restore target. 

The appropriate logic should be that permissions are only restored whenever Corso restores a given item or folder specifically. 

Consider the following original hierarchy:
     Folder A
        -> Folder B (shared with user 1 and user 3)
            -> item Y (shared with user 2)
        -> item X (shared with user 3)
        
 (1) Restoring Item X only
      => the resulting item, wherever it is placed, will be shared with User3

 (2) Restoring item Y only 
      => the resulting item, wherever it is placed, will be shared with User 2
      Note: that this should not change permissions on any parent folders where Item Y maybe placed
      Note: Even though all items in Folder B are restored permissions for the parent folder where these items go should not change

 (3) Restoring Folder A (includes everything in it including item Y) and Item X
     => resulting folderA will be shared with user 1 and user 3
     => resulting item Y (within folder A) will be shared with user 2 explicity. Then folder permissions will apply from Folder A as parent
     => resulting item X will be shared with user 3

**Comment by meain** [comment]
@gmatev All of these conditions are satisfied as of now. The issue is only when a file and its parent folder are given the same permissions for the same user, and that too when the file within the folder is given  the permission first.
