### ISSUE TITLE
`SharePoint.Pages` Feature Tracker 

### ISSUE THREAD

**Issue by dadams39** [alcionai/corso#2173]
Tracks the progress of `SharePoint.Pages`  feature 
- [ ] Enable msgraph-beta-sdk-go for Corso https://github.com/alcionai/corso/issues/2086
- [x] `path.Path` category for Pages https://github.com/alcionai/corso/issues/2109
- [ ]  Create backup details for Pages https://github.com/alcionai/corso/issues/2069
- [x] Display headers for SharePoint https://github.com/alcionai/corso/issues/2090
- [ ] Update Selectors for Backup https://github.com/alcionai/corso/issues/2111
- [ ] Update Selectors for Restore https://github.com/alcionai/corso/issues/2168
- [ ] Backup Site Pages https://github.com/alcionai/corso/issues/2071
- [ ] Restore Site Pages https://github.com/alcionai/corso/issues/2169

Issues found during testing
=====
- [ ] https://github.com/alcionai/corso/issues/2107

**Comment by vkamra** [comment]
@dadams39 - let's track integration tests here as well please

**Comment by dadams39** [comment]
- IF an issue has a PR behind it, the code has been implemented. Even if the PR is approved, it will not be merged until a solution to #2174 is finished. 

- Priority is to showcase a prototype of  `Beta`'s API of `SharePoint.Pages` within Corso's environment.
