### ISSUE TITLE
Per-item failure tracking

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#2708]
## Issue
Corso needs to track its runtime errors with a serializable struct so that error cases can be formalized into per-item references with information that is valuable to end-users. 

## Proposal
```go
// in pkg fault.  eg: fault.Item{}
type Item struct {
  // deduplication identifier; the ID of the backing item.  
  ID string `json:"id"`
  // a human-readable reference: file/container name, email, etc
  Name string `json:"name"`
  // the name of the container inside which this item is stored.
  // may be empty in certain cases (eg: resourceOwner)
  ContainerName string `json:"containerName"`
  // the id of the container inside which this item is stored.
  // may be empty in certain cases (eg: resourceOwner)
  ContainerID string `json:"containerID"`
  // one of: file | container | resourceOwner
  Kind string `json:"kind"`
  // Error() of the causal error, or a sentinel if this is the
  // source of the error.  In case of ID collisions, the first
  // item takes priority.
  Cause string `json:"cause"`
}

func (fi *Item) Error() string {
  // => "processing <Kind>"
}
```

## Acceptance Criteria
- [x] Failed items should generate fault.Item structs as errors.
- [x] Operations consumers (ie: cli, sdk) should have a means of serializing items errors following an operation Run().
- [x] fault.Items should serialize into the backup metadata.
- [x] users should be able to retrieve the list of failed items from a backup by ID.
- [x] users should be able to review errors, item failures, and skips from the `backup list --backup x` command.
