### ISSUE TITLE
Teams & Groups Implementation

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#3988]
High level tracking for Implementation of Teams and Groups support.

# Subtasks
- [x] [Channels Backup](https://github.com/alcionai/corso/issues/3989)
- [x] [Channels Export](https://github.com/alcionai/corso/issues/3991)
- [x] [Libraries Backup](https://github.com/alcionai/corso/issues/3990)
- [x] [Libraries Restore](https://github.com/alcionai/corso/issues/3992)
- [x] #4259
- [x] [Path Extension Support](https://github.com/alcionai/corso/issues/3993)
- [x] #4308
- [x] #4309
- [x] #4310
- [x] https://github.com/alcionai/corso/issues/4462
- [x] https://github.com/alcionai/corso/issues/4431
- [x] https://github.com/alcionai/corso/issues/4430

# Future tech-debt
- https://github.com/alcionai/corso/issues/4312
- https://github.com/alcionai/corso/issues/4405

# Boilerplate Implementation
## Packages / Files

- [x]  `/src/internal/<provider>/<service>` owns all backup/restore/export logic for that provider.
- [x]  `CLI`
    - [x]  `/cli/backup/<service>` to own all cli commands for backups
    - [x]  `/cli/restore/<service>` to own all cli commands for restores
    - [x]  `/cli/export/<service>` to own all cli commands for exports
    - [x]  `/cli/flags/<service>` to own all cli flags for the service
    - [x]  `/cli/utils/<service>` to own all cli utils/flag parsers for the service

## Interface & Data Compliance

- [x]  `/src/pkg/path/resource_path.go` -  canonical enums for representing each service.
- [x]  `/src/pkg/backup/details/<service>.go` - details iteminfo representation for the service.
- [x]  `/src/pkg/selectors/<service>.go` - selectors for the service.

## Enumeration

- [x]  Protected Resources must have an enumeration api available in the `/src/pkg/services/<provider>/_.go` file, to be consumed by SDK users.
- [x]  Protected Resources must have an enumeration api available in the `/src/pkg/services/<provider>/api/_.go` file, to be consumed internally.

**Comment by vkamra** [comment]
Closing this issue now. Future work will be tracked by separate tickets
