### ISSUE TITLE
Onedrive Backup Delta Tree

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#4688]
Work related to replacing the onedrive delta processing with a delta tree.

- [x] Introduce the tree/node structures. (https://github.com/alcionai/corso/issues/4689)
- [x] Add a configuration feature-flag to toggle backup-by-tree. (https://github.com/alcionai/corso/issues/4690)
- [x] In Collctions.Get(), branch code by feature flag into the current or tree handling. (https://github.com/alcionai/corso/issues/4691)
- [x] Add support in the tree path for consuming the delta operation. (https://github.com/alcionai/corso/issues/4691)
- [x] Add support in the tree path for incorporating previous paths. (https://github.com/alcionai/corso/issues/4691)
- [x] Add tree post-processing. (https://github.com/alcionai/corso/issues/4689)
- [x] Reverse the feature flag to toggle runs the old flow. (https://github.com/alcionai/corso/issues/4690)
- [x] Release the refactor.
- [ ] Cleanup: remove the feature flag.  (https://github.com/alcionai/corso/issues/4690)
- [ ] Cleanup: remove the old code flow. (https://github.com/alcionai/corso/issues/4691)
